[build]
base = "/"
command = "pnpm -F @proj-airi/TEMPLATE_ID... run build"
publish = "/apps/TEMPLATE_ID/dist"

[build.environment]
NODE_VERSION = "23"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
