[build]
base = "/"
command = "pnpm -F @proj-airi/yolov9-object-detection-realtime-webgpu... run build"
publish = "/apps/yolov9-object-detection-realtime-webgpu/dist"

[build.environment]
NODE_VERSION = "23"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
