[build]
base = "/"
command = "pnpm -F @proj-airi/whisper-webgpu... run build"
publish = "/apps/whisper-webgpu/dist"

[build.environment]
NODE_VERSION = "23"

[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
